### ISSUE TITLE
Yes, I manually modified the cultivar value in DSSAT and it worked.

### ISSUE THREAD

**Issue by taynaravaleriano** [daquinterop/Py_DSSATTools#11]
Yes, I manually modified the cultivar value in DSSAT and it worked. 
Could you, please, check if it is possible to manage this in fortran?

_Originally posted by @taynaravaleriano in https://github.com/daquinterop/Py_DSSATTools/issues/10#issuecomment-1669598623_

**Comment by daquinterop** [comment]
Hi Taynara. I just fixed that issue and push the last changes. Thanks for letting me know. Please install the last version from the repository and let me know if it works.

**Comment by taynaravaleriano** [comment]
Hi Diego, thank you for your support. 
However is not working yet, when I try to run with values like 1000, it gives me an error, and in the CUL file the values stays like this: 

![image](https://github.com/daquinterop/Py_DSSATTools/assets/141453857/9a834f2c-7ef1-4954-b769-cb1049e16874)

**Comment by daquinterop** [comment]
How did you installed the latest version?

**Comment by taynaravaleriano** [comment]
Yes, I run:

pip install DSSATTools

**Comment by daquinterop** [comment]
Ok. That'll install the latest version I uploaded to PyPI. I won't upload the latest changes to PyPI until I'm sure the fix works. So, please do this:

First uninstall the library:
```
pip uninstall DSSATTools
```
Then clone the repository and install it from it:
```
git clone https://github.com/daquinterop/Py_DSSATTools
cd Py_DSSATTools
pip install -e .
```

Try that and let me know if it works

**Comment by taynaravaleriano** [comment]
Hii Diego, it worked! 

Thank you so much!
