### ISSUE TITLE
output

### ISSUE THREAD

**Issue by qianweihao** [daquinterop/Py_DSSATTools#12]
Is the output only plantGro?

**Comment by daquinterop** [comment]
Hi. Yes, it is the only output so far. What output do you need? Maybe I can include it for the next release.

**Comment by qianweihao** [comment]
Hello, I feel that one output is a bit less. It would be great if you can choose the output file to DSSAT software, such as Evaluate.OUT and SoilWat.OUT

**Comment by qianweihao** [comment]
> Hi. Yes, it is the only output so far. What output do you need? Maybe I can include it for the next release.

Hello, I feel that one output is a bit less. It would be great if you can choose the output file to DSSAT software, such as Evaluate.OUT and SoilWat.OUT

**Comment by daquinterop** [comment]
The soil carbon and water balance outputs will be included in the near future. Thanks for the suggestion. I'll keep this issue opened while the outputs are included. However if you need to check other outputs not implemented now, you can always check at the directory where DSSAT is running and read the outputs as you would read any text file. That directory is assigned to the `DSSAT` instance you're using as your simulation environment (let's say dssat), so you the path is in `dssat._RUN_PATH`

**Comment by daquinterop** [comment]
Hi @qianweihao I included the suggested output files. You should be able to get the latest version of the library by installing it via pip or directly from the repo.
