### ISSUE TITLE
plant population (plant/m2) variable

### ISSUE THREAD

**Issue by moniquebranco** [daquinterop/Py_DSSATTools#15]
Hi @daquinterop

I did not find the "plant population, plant/m2 (PLTPOP)" variable in the management module - self.planting_details. This information is mandatory in the DSSAT GUI interface, as "Potential dry matter production (PCARB)" is calculated from this variable:
PCARB = IPAR * RUE * PCO2
IPAR = PAR/PLTPOP * (1.0 - EXP(-LIFAC * LAI))
LIFAC  = 1.5 - 0.768 * ((ROWSPC * 0.01)**2 * PLTPOP)**0.1

How is the calculation done? In my case, I need to add this variable, because my framework depend on it. How could I compute it?

Thank you!
Monique

**Comment by moniquebranco** [comment]
I forgot to say that I am working with ceres-maize. Did the PPOP the same as PLTPOP?

**Comment by daquinterop** [comment]
Hi Monique. Exactly, PPOP is the plant population at seedling, and PPOE is the plant population at emergence.
