### ISSUE TITLE
WANT TO CALCULATE YEAR CROP YEILD BUT ARE STUCK RIGHTNOW.......! 

### ISSUE THREAD

**Issue by mhwahla** [daquinterop/Py_DSSATTools#17]
Hello @daquinterop, I have data  of one year weather, soil conditions, and crop management information. Within the domain of crop management, I have also nitrogen levels and biomass with 50 treatments. Our objective is to utilize this dataset for a year crop simulation, I wants outcomes biomass and yield.
Actually, we are following this as input and output.  (https://github.com/maso0310/DSSAT_Test/blob/master/01_DSSAT_for_Rice.py)

after this comment of yours 
![image](https://github.com/daquinterop/Py_DSSATTools/assets/51794945/8251a5a9-6dc6-40ae-a639-6eefe7bd976a)
we changed CWD TO GWD 
BUT GOT A STRAIGHT LINE LIKE THIS 
![image](https://github.com/daquinterop/Py_DSSATTools/assets/51794945/aa25ab3f-e481-416e-b411-cd34d92aee01)

We want a simple solution(excel input/ excel output) as we are not that adept pandas users. 

THANKS FOR YOUR WONDERFUL CONTRIBUTION TO PYTHON COMMUNITY.

**Comment by daquinterop** [comment]
Hi. I didn't write the script you're following, so I really don't know what you're trying to plot and how it is supposed to look like. I recommend you to follow this example notebook: https://github.com/daquinterop/DSSATTools_notebooks/blob/main/Example%201%20(Basics).ipynb 

If you want to have your output as an excel file you can just export it to csv using the `to_csv` method. The generated output is a pandas dataframe, so if you want to export the Plant Growth output to a csv file you just have to do something like `dssat.output['PlantGro'].to_csv("path/to/your/file")` .

**Comment by mhwahla** [comment]
Hello Daquinterop, thanks so much for your reply, I had run and exlpored
all 4 of your of the example notebooks.

You have done awesome work.

I am following on your this recent comment and I will get back to you soon.

Regards.
