### ISSUE TITLE
CO2048.WDA is outdated compared to DSSAT

### ISSUE THREAD

**Issue by osherboudara-work** [daquinterop/Py_DSSATTools#18]
Hey @daquinterop! 

Hope you are doing well. I wanted to reach out and let you know that your CO2 file is a bit outdated. It seems your file only goes up to 2021 while the DSSAT file goes up to 2023. Wanted to let you know as noticed my CO2 values were a bit off after 2021. Here is a link to the file I am referring to:
https://github.com/DSSAT/dssat-csm-os/blob/release/Data/StandardData/CO2048.WDA

Thanks for all your work on this amazing package!

**Comment by osherboudara-work** [comment]
Here is the link to your file for your reference:
https://github.com/daquinterop/Py_DSSATTools/blob/main/DSSATTools/static/StandardData/CO2048.WDA

**Comment by daquinterop** [comment]
Hi. Thanks for the heads up. Just updated it, I'll push it later when some major changes I'm implementing are ready.

**Comment by osherboudara-work** [comment]
Hello again @daquinterop!

Thanks for the update. Let me know when you push the changes. Appreciate all your work!
