### ISSUE TITLE
Wheat crop simulation

### ISSUE THREAD

**Issue by mishagrol** [daquinterop/Py_DSSATTools#19]
Hello! ✋

Is it possible to add wheat here - https://github.com/daquinterop/Py_DSSATTools/blob/09efc7142e255a84e09bd1f04329e419abafbc9b/DSSATTools/crop.py#L104 ?

Or is it more complex task than just line of code, other model?)

**Comment by daquinterop** [comment]
Hi Mikhail. I'm currently working on implementing Wheat and Barley. It's been more complex than the other models, so it probably will take some time. I'll let you know here when that's done.

**Comment by daquinterop** [comment]
Hi Mikhail and all interested. I included wheat, you can check the latest version in the [wheat branch](https://github.com/daquinterop/Py_DSSATTools/tree/wheat). You can install the library from that branch. If you do so please let me know if it's working. I'll be working on other things before submitting the latest version to PyPI.

**Comment by mishagrol** [comment]
Wow, thanks! I will test it in next two weeks!!)

**Comment by osherboudara-work** [comment]
Hello @daquinterop!

Hope you are doing well. I was wondering what the status of this update is. I would love to execute some simulations for wheat using this library.

Thank you for all your hard work on this amazing library!

**Comment by daquinterop** [comment]
Hi @osherboudara-work. Wheat CERES model is now included. You can use it by updating to the latest version (2.1.2). Thanks for your interest in the project and I'm sorry it took me a while to get back to you.

**Comment by osherboudara-work** [comment]
Hi @daquinterop!

Thanks for merging it. I am having an error running the model now. For some reason, when I try to run any simulations, I get this error attached in the screenshot below. Any idea why this might be happening?

<img width="374" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/3c2db864-46ea-445b-bead-21be5e159889">

Thank you again!

**Comment by osherboudara-work** [comment]
@daquinterop, this is also occurring for my tomato and soybean simulations. I hope there is a fix for this soon so I can continue using the library. Thank you again for all your hard work!

**Comment by daquinterop** [comment]
@osherboudara-work can you share your code so that I can reproduce the issue?

**Comment by osherboudara-work** [comment]
@daquinterop The error is occurring at the dssat.run() call. I have set up my weather, crop, soil and agro-management components using the same methodologies as in your DSSAT notebooks Github so the error should occur in those notebooks as well. My simulations were executing fine in the 2.1.1 version of this library but once I updated, I started getting the error above in my various scripts. Let me know if there is any additional information you need.

**Comment by daquinterop** [comment]
Well, everything is working fine on my side when I run the notebooks. It might be a problem in the formatting of the inputs, but there is no way of knowing it unless I have the script/notebook you're running, or the contents of the folder where DSSAT is running (DSSAT._RUN_PATH).

**Comment by osherboudara-work** [comment]
@daquinterop 
<img width="422" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/ab5573af-0229-466c-9936-63da99ea8071">
<img width="353" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/aca9957b-137d-48d7-a479-b5576b6624c2">
<img width="271" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/46278643-4ac6-4934-95f1-94d1b928c205">
<img width="283" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/701986b1-9a37-4240-9b4d-0bb0ce635b42">
<img width="543" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/ae53df55-f9c9-44c2-b3f4-ffab971ec0b1">

Here are screenshots of how I set up my different modeling components. When looking at error.out file, this is what it shows:

<img width="233" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/6b9f63d9-0ffd-48c8-bc31-90a486f91b44">


And this is what the warning.out file looks like:

<img width="287" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/347b4528-8c28-4127-8861-419b32a54c5f">

Let me know if there is more information you need.

**Comment by daquinterop** [comment]
I can't see the crop definition there, is it tomato and default cultivar?

**Comment by osherboudara-work** [comment]
@daquinterop My mistake, I forgot to include that screenshot. Here it is:
<img width="204" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/34b9dae4-83e5-4957-b08e-7798015246bb">

**Comment by daquinterop** [comment]
Are you modifying any crop parameter? 

I'm afraid I still can't reproduce the error with the information you shared. It would help if you attach the notebook or a Python script, or if you copy and paste your code here

**Comment by osherboudara-work** [comment]
@daquinterop, here is the full code, I am getting the same error I sent above for any crop I use:


# Import relevant functions from DSSAT Model
from DSSATTools import Crop, SoilProfile, SoilLayer, Weather, Management, DSSAT, available_cultivars
import DSSATTools


# Additional Imports 
import pandas as pd 
from datetime import datetime, timedelta
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time

## Weather Data Instance Initialization

# All the weather variables that the model can use
DSSATTools.weather.list_weather_variables()

# Creates range of dates
dates = pd.date_range('2000-07-01', '2010-12-31') # change here

# Gets the amount of dates
num_dates = len(dates)

# Sets a random seed
np.random.seed(9)

# Generation of weather data
df = pd.DataFrame(
        {
            'tn': np.random.gamma(10, 1, num_dates),  # sets min temperature # change here
            'rad': np.random.gamma(10, 1.5, num_dates), # sets solar radiation  # change here
            'prec': [0.0] * num_dates, # precipitation   # change here
            'rh': 100 * np.random.beta(1.5, 1.15, num_dates) # sets relative humidity   # change here
                                                                                   # include another weather variable
        },
    index=dates
)

# creation of max temperature
df['TMAX'] = (df.tn + np.random.gamma(5,5,num_dates)) 
df

# Set arbitrary coordinates and elevation
test_lat = 32.642 #change here
test_lon = -116.25 #change here
elevation = 838.61 #change here

elevation

# All the weather variables that the model can use
DSSATTools.weather.list_weather_variables()

# Create a WeatherData instance using the DSSAT Library

weather_data = Weather(df, # pass in dataframe
       {
           'tn': 'TMIN', 'TMAX':'TMAX', # set column in dataframe to what is expected in the weather function above
           'prec': 'RAIN', 'rad':'SRAD',
           'rh':'RHUM',                 # include another weather variable
       }, test_lat, test_lon, elevation)
weather_data

## SoilProfile object

You can use a default soil profile, or you can create your own soil profile. To check the available soil profiles you can use the help function to check the docstring of the SoilProfile class


help(SoilProfile)

# Creating a default soil profile
soil = SoilProfile(default_class='L') # change here

# How Soil file looks
soil

That's the easy way of definig your soil. However, if you have enough data you can define your soil. A SoilProfile object is a series of stacked SoilLayer objects. Each layer can have different properties, and you can define them separately. You define your custom soil profile in two steps:

1) Initialize the instance. A dictionary with the profile properties have to be defined. \
2) Create the soil layers that will conform that SoilProfile. You need to indicate the depth and properties of that layer. \
3) Add the layers to the soil. \
For each layer you can define the as many parameters as you want. However, if you only have the soil texture, the rest of the parameters will be calculated from the texture. That's what we'll do next:

# soilprofile = SoilProfile(
#     pars={
#         'SALB': 0.25, # Albedo
#         'SLU1': 6, # Stage 1 Evaporation (mm)
#         'SLPF': 0.8 # Soil fertility factor
#     }
# )
# layers = [
#     SoilLayer(20, {'SLCL': 50, 'SLSI': 45}),
#     SoilLayer(50, {'SLCL': 30, 'SLSI': 30}),
#     SoilLayer(80, {'SLCL': 32, 'SLSI': 31}),
#     SoilLayer(110, {'SLCL': 30, 'SLSI': 35}),
#     SoilLayer(140, {'SLCL': 24, 'SLSI': 33}),
#     SoilLayer(170, {'SLCL': 20, 'SLSI': 30})
# ]
# for layer in layers: 
#      soilprofile.add_layer(layer)
# soilprofile

# Create a Crop object from default crop file

help(Crop)

# Check the available cultivars available
available_cultivars('tomato') # change here

# Crop
crop = Crop('tomato', 'TM0007') # change here

# cultivar parameters
crop.cultivar

## Create a management instance

# Management file
help(Management)

dates

# Pass in index of planting date and initialize management practices
agro_management = Management(
    planting_date=dates[10]) # change here

agro_management.planting_details

agro_management.harvest_details

agro_management.planting_details.description

# Modify harvest to maturity
agro_management.simulation_controls['HARVS'] = 'M'

## Setup the Simulation Environment and Run the Model

# View Weather object previously created
weather_data

# Initialize dssat
dssat = DSSAT()

# initialize DSSAT output location
dssat.setup()

# capture time
st = time.time()

# model execution with relevant parameters
dssat.run(
    soil=soil, weather=weather_data, crop=crop, management=agro_management
)
et = time.time()

# Print model execution time
print(f'\nElapsed time: {et-st:,.2f} s')

# Store output
output_1 = dssat.output['PlantGro']

output_1.columns

output_1

output_1.CWAD.max()

# remove DSSAT output files
dssat.close()

**Comment by daquinterop** [comment]
Run `crop.ecotype` and show me how it looks. It should look exactly like this:

```
Ecotype section
  Parameters:
    @ECO#: TM0001
    ECONAME..........: SEMI-DETERMINATE 
    MG: 01
    TM: 01
    THVAR: 0.0
    PL-EM: 6.0
    EM-V1: 22.0
    V1-JU: 0.0
    JU-R0: 5.0
    PM06: 0.55
    PM09: 0.75
    LNGSH: 39.0
    R7-R8: 0.0
    FL-VS: 24.5
    TRIFL: 0.45
    RWDTH: 1.0
    RHGHT: 1.0
    R1PPO: 0.0
    OPTBI: 0.0
    SLOBI: 0.0
    XMAGE: 10.0
```

**Comment by osherboudara-work** [comment]
@daquinterop:

<img width="204" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/520d8e86-b8d4-476d-8b0b-f02dd51d7652">

**Comment by osherboudara-work** [comment]
@daquinterop here's how the output directory looks after the error occurs. I reattached the error here again:

<img width="181" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/1a96eca2-20cc-4b9b-84b2-af33927b566d">
<img width="456" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/166391a3-7027-4796-9613-1d48e9c69266">

**Comment by daquinterop** [comment]
Please show me that TMGRO048.ECO file, I need to see how it looks like

**Comment by osherboudara-work** [comment]
@daquinterop, i copy and pasted the full file here:

```
*TOMATO ECOTYPE COEFFICIENTS: CRGRO048 MODEL
@ECO#  ECONAME.......... MG TM THVAR PL-EM EM-V1 V1-JU JU-R0  PM06  PM09 LNGSH R7-R8 FL-VS TRIFL RWDTH RHGHT R1PPO OPTBI SLOBI XMAGE
TM0001 SEMI-DETERMINATE  01 01   0.0   6.0  22.0   0.0   5.0  0.55  0.75  39.0   0.0 24.50  0.45   1.0   1.0 0.000   0.0 0.000  10.0

```

**Comment by daquinterop** [comment]
Well that looks all good. I ran your code and everything was ok, so I really don't know what could be wrong. Try to uninstall the package and install it again. If the error persists please zip the entire output directory (/tmp/dssatmlmxsnin) and attach it here.

**Comment by osherboudara-work** [comment]
@daquinterop, I have tried to uninstall and reinstall multiple times and it doesn't work. Only thing that does work is using the older version of the library (2.1.1). I should let you know that I am using a Ubuntu based cloud environment to run these simulations. I have attached the zip file of another failing simulation (not the same directory you specified above but with the same issue occurring). Let me know if you need any additional information.
[DSSATPRO.zip](https://github.com/daquinterop/Py_DSSATTools/files/14069782/DSSATPRO.zip)

**Comment by osherboudara-work** [comment]
@daquinterop, keep me posted on a potential fix. I sent the error above and it seems there is a sort of assertion error due to some updates that were made from 2.1.1 to 2.1.2, I never had this assertion error in 2.1.1. I would love to continue using this library if there is a fix, for now I will uninstall the 2.1.2 and continuing using 2.1.1 as I cannot run any simulations on 2.1.2.

Thank you for all your work on this library.

**Comment by daquinterop** [comment]
Just a question. Does it work with other crops? or is it just not working at all?

**Comment by daquinterop** [comment]
@osherboudara-work I think I found the bug, a significant one. I think I just fixed it. Could you please install it from the latest version in the repository? 
```
git clone https://github.com/daquinterop/Py_DSSATTools
cd Py_DSSATTools
pip install -e .
```
Let me know if that works to push the latest changes to PyPI
