### ISSUE TITLE
read an existing weather file (WTH)

### ISSUE THREAD

**Issue by taynaravaleriano** [daquinterop/Py_DSSATTools#24]
Hi @daquinterop , how are you?

I would like to know if it is possible to read a WTH file, instead of creating one to run

**Comment by daquinterop** [comment]
Hi @taynaravaleriano. There is not the option of creating a Weather object by reading a WTH file. However, it is really easy to read the WTH file using pandas, to latter use it to create a Weather instance. You can see and example [here](https://github.com/daquinterop/Py_DSSATTools/blob/736d2c80e91c8c2c3aa5bc3fbc408a8e8540fc1e/tests/test_run.py#L74).
