### ISSUE TITLE
Simulation fails with new release (2.1.2)

### ISSUE THREAD

**Issue by daquinterop** [daquinterop/Py_DSSATTools#25]
Hi @daquinterop!

Thanks for merging it. I am having an error running the model now. For some reason, when I try to run any simulations, I get this error attached in the screenshot below. Any idea why this might be happening? The ERROR.OUT file isn't being outputted.

<img width="374" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/3c2db864-46ea-445b-bead-21be5e159889">

Thank you again!

_Originally posted by @osherboudara-work in https://github.com/daquinterop/Py_DSSATTools/issues/19#issuecomment-1912651577_

**Comment by osherboudara-work** [comment]
https://github.com/daquinterop/Py_DSSATTools/issues/19#issuecomment-1912879326

@daquinterop, replying to your message from the link above. I have tested the edited library that you provided through the git clone command and the simulations are working for me across the existing crops (tested tomato and soybean and both work). The simulation for wheat also worked but I am getting an error on the available_cultivars() function. I am still able to set the Crop function to wheat which allows the simulation to execute but it doesn't allow me to view the cultivars via available_cultivars(). I have attached a screenshot of the error.

<img width="464" alt="image" src="https://github.com/daquinterop/Py_DSSATTools/assets/122553959/5c5bc2c2-4670-4827-8874-44f4199bb0fa">

**Comment by daquinterop** [comment]
Hi @osherboudara-work, I just fixed that problem. You can install it from the repo again. Please let me know if it works to push the latest changes to PyPI. Thanks for reporting this issue

**Comment by osherboudara-work** [comment]
Hi @daquinterop!

I just reinstalled the library from the repo and the simulations for wheat (including the available_cultivars() function) work! I would say it is safe to push the changes to PyPI. 

Thank you for all your hard work on this library! Let me know when you make the update to PyPI.

**Comment by daquinterop** [comment]
Thanks for letting me know. I just made the update to PyPI
