### ISSUE TITLE
Decoding error

### ISSUE THREAD

**Issue by mikededad** [daquinterop/Py_DSSATTools#3]
Hello, when I run test_ When running. py, an error occurs, and an error is reported in line 41,How to solve it.

tests/test_run.py:None (tests/test_run.py)
test_run.py:41: in <module>
    soil = SoilProfile(default_class='SIL')
..\..\..\..\anaconda3\envs\pywofost_4_0_0(1)\lib\site-packages\DSSATTools\soil.py:394: in __init__
    self._open_file()
..\..\..\..\anaconda3\envs\pywofost_4_0_0(1)\lib\site-packages\DSSATTools\soil.py:482: in _open_file
    for line in f:
E   UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 3342: illegal multibyte sequence

**Comment by daquinterop** [comment]
Hi mikededad, can you give details on the OS and Python version you're using?

**Comment by mikededad** [comment]
windows10   python3.10

**Comment by mikededad** [comment]
Hello. What's the final result supposed to be? Can DSSAT model output crop-related growth information?

**Comment by daquinterop** [comment]
Hello mikededad. I'll be taking a look at the error you're reporting later today. Regarding the output, when DSSAT runs it creates a set of output files that you can check them here: https://github.com/DSSAT/dssat-csm-os/blob/develop/Data/OUTPUT.CDE. However, DSSATTools only parses the PlantGro.OUT file. So, the answer to your question is yes, one of DSSAT's output files describes the daily growth information of the crop, and up to date is the only file parsed by DSSATTools. Please do not hesitate to reach out if you have more questions.

**Comment by mikededad** [comment]
Thank you very much. I'm test_ru.py an error with no results

**Comment by daquinterop** [comment]
You're not supposed to get any output after running test files. To check if the library is working properly and explore their features and outputs you should better run the example notebooks. I recommend you to go over the basic example: https://github.com/daquinterop/DSSATTools_notebooks/blob/main/Example%201.ipynb

**Comment by mikededad** [comment]
Hello, it still reported an error when executing the soil.
for example 
# Soil instance from default soil profile
soil = SoilProfile(default_class='SIL')
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_20876\1385550301.py in <module>
      1 # Soil instance from default soil profile
----> 2 soil = SoilProfile(default_class='SIL')

~\anaconda3\lib\site-packages\DSSATTools\soil.py in __init__(self, file, profile, default_class, pars)
    392             )
    393             self.id = DEFAULT_PROFILES_IDS[default_class]
--> 394             self._open_file()
    395         else:
    396             self._file_initilized = False

~\anaconda3\lib\site-packages\DSSATTools\soil.py in _open_file(self)
    480         FOUND_PROFILE = False
    481         with open(self._file_path, 'r') as f:
--> 482             for line in f:
    483                 stiped_line = line.strip()
    484                 if len(stiped_line) == 0:

UnicodeDecodeError: 'gbk' codec can't decode byte 0xbd in position 3342: illegal multibyte sequence

**Comment by daquinterop** [comment]
Hi. I tried to reproduce the error on my laptop using the same OS and Python Version you're using (3.10.7), however wasn't able to do it. 
I do recommend you to run it again changing the `default_class` parameter to a different value. You can try with these: S, SL, LS, L, SI, SCL, CL, SICL, SC, SIC, C. For example, instead of running `soil = SoilProfile(default_class='SIL')`, run `soil = SoilProfile(default_class='LS')` and let me know if it works with any of the options I just provided. This would help me to understand if there's a encoding error on the default soil files included with the library.

Thanks for your patience.
