### ISSUE TITLE
How the DSSAT.run simulates the cop photosynthesis and development?

### ISSUE THREAD

**Issue by Zyt526** [daquinterop/Py_DSSATTools#32]
Hi there. The py_DSSAT is so good and I really like your work. However, as a newbie, I'm a little confused. I'm trying to find out how it simulates photosynthesis and growth in DSSAT.run() but I'm not finding it clearly. Do you mind sharing some clues?

**Comment by daquinterop** [comment]
Hello. The processes are not simulated on Python. This library is only a wrapper to the CSM which is written on FORTRAN. You can see the details on the [DSSAT github repo](https://github.com/DSSAT/dssat-csm-os), or review the [Key publications](https://dssat.net/training/key-publications/).
