### ISSUE TITLE
FMT encode in .CUL & .ECO files not properly set 

### ISSUE THREAD

**Issue by ibrahimasow** [daquinterop/Py_DSSATTools#35]
When reading the values in .CUL or .ECO files, you use ff.FortranRecordReader() and fortran FMT codes ("A5,1X,..."). 
However with wheat (**I presume that the same error might occur with other crops**) some of the columns on the cultivar file (.cul) are mixes of integers and floats, then using a single data type to map it with FMT codes you get some values that are converted into another type. 

To reproduce you can use the WHCER048.CUL file:

> *CULTIVARS:WHCER048
> @VAR#  VAR-NAME........  EXP#   ECO#   P1V   P1D    P5    G1    G2    G3 PHINT
> !Coeffient #                             1     2     3     4     5     6     7
> !Calibration                             P     P     P     G     G     G     N
> !                                     Vday %/10h  oC.d   #/g    mg     g  oC.d
> 999991 MINIMA               . 999991     0     0   100    10    10   0.5    30
> 999992 MAXIMA               . 999992    60   200   999    50    80   8.0   150

When running something like this (from the DSSATTolls.Crop and DSSATTools.Section classes):

```
_crop_name = crop_name.title()
assert (
    _crop_name in CROPS_MODULES.keys()
), f"{_crop_name} is not a valid crop"
_SMODEL = CROPS_MODULES[_crop_name]
_CODE = CROP_CODES[_crop_name]
_SPE_FILE = f"{_CODE}{_SMODEL[2:]}{VERSION}.SPE"
_spe_path = os.path.join(GENOTYPE_PATH, _SPE_FILE)
_cultivar_code = cultivar_code
if _cultivar_code is None:
    _cultivar_code = DEFAULT_CULTIVARS[_crop_name]
    warnings.warn(
        f"No cultivar was indicated, default cultivar {_cultivar_code} will be used"
    )

# Read cultivar
cul_file = _spe_path[:-3] + "CUL"
with open(cul_file, "r") as f:
    file_lines = f.readlines()
file_lines = clean_comments(file_lines)
cultivar = Section(
    name="cultivar",
    file_lines=file_lines,
    crop_name=_crop_name,
    code=_cultivar_code,
)
_cultivar_code = cultivar["@VAR#"]
cultivar
```

You end up with: 

>  Cultivar section
>   Wheat crop
>   Parameters:
>     @VAR#: 999991
>     VAR-NAME........: MINIMA          
>     EXP#:     .
>     ECO#: 999991
>     P1V: 0.0
>     P1D: 0.0
>     P5: 10.0
>     G1: 1.0
>     G2: 1.0
>     G3: 0.5
>     PHINT: 3.0 (see here)

Notice values for  PHINT for instance (3.0 in this output but on the WHCER048.CUL file), it is 30. 

I think issue is on the FMT coding: 

> "Wheat": "A6,1X,A16,1X,A5,1X,A6,5(1X,F5.1),1X,F5.2,1X,F5.1"

Last column (PHINT is declared as F5.1 (I guess it is to be able to extract values for all the rows containing MANITOU, NEWTON, MARIS FUNDIN cultivars  but this turns integers like 30 to 3.0 for other cultivars (e.g., 999991) 

Thank you

**Comment by daquinterop** [comment]
Hi Ibrahima, thanks for your work on spotting this issue. I just got it fixed and pushed the latest changes to the main branch of the repo. Let me know if that fixed the issue to include those changes in the next PyPI push. Thanks.

**Comment by ibrahimasow** [comment]
Great, thank you, Diego!
