### ISSUE TITLE
OSError: [WinError 1314] A required privilege is not held by the client

### ISSUE THREAD

**Issue by eusojk** [daquinterop/Py_DSSATTools#39]
First off, thanks very much, dear @daquinterop, for open-sourcing a fantastic tool like this. I (and I am sure the community also) appreciate your efforts!

## Information

Upon a successful install, I followed along with the notebooks from [Example 1 (Basics).ipynbs](https://github.com/daquinterop/DSSATTools_notebooks/blob/main/Example%201%20(Basics).ipynb). I ran into the following issue:

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[6], line 1
----> 1 from DSSATTools import (
      2     Crop, SoilProfile, Weather, Management, DSSAT, SoilLayer,
      3     available_cultivars
      4 )
      5 import DSSATTools
      6 import pandas as pd

File c:\Users\self\AppData\Local\anaconda3\envs\ee\Lib\site-packages\DSSATTools\__init__.py:78
     76 from DSSATTools.weather import Weather
     77 from DSSATTools.management import Management
---> 78 from DSSATTools.run import DSSAT
     79 from DSSATTools.base.sections import TabularSubsection
     81 __all__ = [
     82     'Crop', 'SoilProfile', 'SoilLayer', 'Weather', 'Management', 'DSSAT', 
     83     'TabularSubsection', "available_cultivars"
     84     ] 

File c:\Users\self\AppData\Local\anaconda3\envs\ee\Lib\site-packages\DSSATTools\run.py:63
     61     if os.path.exists(file_link):
     62         os.remove(file_link)
---> 63     os.symlink(os.path.join(STATIC_PATH, file), file_link)
     65 if 'windows'in OS:
     66     BIN_PATH = os.path.join(STATIC_PATH, 'bin', 'dscsm048.exe')

OSError: [WinError 1314] A required privilege is not held by the client: 'c:\\Users\\self\\AppData\\Local\\anaconda3\\envs\\ee\\Lib\\site-packages\\DSSATTools\\static\\bin' -> 'C:\\Users\\self\\AppData\\Local\\Temp\\DSSAT048\\bin'
```

I thought it would be more fitting to open up the issue here instead of over at  [DSSATTools_notebooks](https://github.com/daquinterop/DSSATTools_notebooks). But please let me know if I should add the issue over there instead.

## Environment info

- `dssattools` version: 2.1.3
- Python version: 3.12 (via a `conda` env)
- Conda: 24.5.0
- Platform: Windows 11

## To reproduce

Steps to reproduce the behavior (after installing the library): 
- install library
- clone https://github.com/daquinterop/DSSATTools_notebooks
- open file `Example 1 (Basics).ipynb` in VSCode & run the first cell

## Temporary Workaround

- Open up a `conda` command prompt with Admin privileges
- Activate the right conda env (where `dssattools` is installed)
- Convert the `Example 1 (Basics).ipynb` notebook into a Python script
- And run the script

The steps above seem to indicate that `dssattools` requires elevated/Admin privileges on Windows before running. So, this could be a potential source of the problem? Because, I ran into the same problem when executing the script in a non-Admin `Python/conda` env. Is this Admin requirement necessary for `dssattools`?

Thanks very much in advance for your assistance!

**Comment by danialll1** [comment]
Hello my friend
first thing I would like to stack up your gratitude words for this lovely package
second as a user the only way that I could utilize this package(DSSATTools) was using through a administrator permission.
so I'm pretty sure to need that permission.
Best

**Comment by daquinterop** [comment]
Hi @danialll1. I'm sorry for the delayed response. I don't use the library in Windows, so I don't know what are the required permissions in windows. It makes sense that you need elevated privileges, after all windows is very picky when executing third party software, and that's what you do when you run dssat. 

I highly recommend you to use the library under WSL in windows. That's the best workaround as of my opinion.

Thanks for reporting this

**Comment by eusojk** [comment]
Thanks for replying to my question @daquinterop. Can you please clarify this for future users? e.g., putting this as a note in the docs/README?
