### ISSUE TITLE
Fertilizer input

### ISSUE THREAD

**Issue by ddjustina** [daquinterop/Py_DSSATTools#44]
I’m having issues with the fertilizer specification in DSSATTools. When I compare the OVERVIEW file from a simulation using a default experiment in DSSAT, I get information in the Resource Productivity section regarding the N uptake. However, in DSSATTools, I don’t get any information on this, and the yield is expected to be much higher.

Could you please provide a notebook example where you specify the fertilization?

---------------------------------------------------------------------------------------------------------------

SIMULATION USING DSSAT (a default experiment)
[OVERVIEW_dssat.txt](https://github.com/user-attachments/files/17599846/OVERVIEW_dssat.txt)

*Resource Productivity
 Growing season length: 140 days 

 Precipitation during growing season       360.3 mm[rain]
   Dry Matter Productivity                  2.55 kg[DM]/m3[rain]          =   25.5 kg[DM]/ha per mm[rain]
   Yield Productivity                       0.88 kg[grain yield]/m3[rain] =    8.8 kg[yield]/ha per mm[rain]

 Evapotranspiration during growing season  325.6 mm[ET]
   Dry Matter Productivity                  2.82 kg[DM]/m3[ET]            =   28.2 kg[DM]/ha per mm[ET]
   Yield Productivity                       0.97 kg[grain yield]/m3[ET]   =    9.7 kg[yield]/ha per mm[ET]

 Transpiration during growing season       164.4 mm[EP]
   Dry Matter Productivity                  5.59 kg[DM]/m3[EP]            =   55.9 kg[DM]/ha per mm[EP]
   Yield Productivity                       1.93 kg[grain yield]/m3[EP]   =   19.3 kg[yield]/ha per mm[EP]

 N applied during growing season             70. kg[N applied]/ha
   Dry Matter Productivity                 131.3 kg[DM]/kg[N applied]
   Yield Productivity                       45.2 kg[yield]/kg[N applied]

 N uptake during growing season              128 kg[N uptake]/ha
   Dry Matter Productivity                  71.8 kg[DM]/kg[N uptake]
   Yield Productivity                       24.7 kg[yield]/kg[N uptake]

---------------------------------------------------------------------------------------------------------------
SIMULATION USING DSSATTools

[OVERVIEW_dssattools.txt](https://github.com/user-attachments/files/17599837/OVERVIEW_dssattools.txt)

*Resource Productivity
 Growing season length: 116 days 

 Precipitation during growing season       334.4 mm[rain]
   Dry Matter Productivity                  5.53 kg[DM]/m3[rain]          =   55.3 kg[DM]/ha per mm[rain]
   Yield Productivity                       1.16 kg[grain yield]/m3[rain] =   11.6 kg[yield]/ha per mm[rain]

 Evapotranspiration during growing season  470.8 mm[ET]
   Dry Matter Productivity                  3.93 kg[DM]/m3[ET]            =   39.3 kg[DM]/ha per mm[ET]
   Yield Productivity                       0.82 kg[grain yield]/m3[ET]   =    8.2 kg[yield]/ha per mm[ET]

 Transpiration during growing season       350.2 mm[EP]
   Dry Matter Productivity                  5.28 kg[DM]/m3[EP]            =   52.8 kg[DM]/ha per mm[EP]
   Yield Productivity                       1.11 kg[grain yield]/m3[EP]   =   11.1 kg[yield]/ha per mm[EP]

**Comment by daquinterop** [comment]
Hi. You can only have that output in the overview file when you have the Nitrogen switch on. By default it is off, so you have to turn in on. To do that you just do `man.simulation_controls["NITRO"] = "Y"`, where `man` is a `Management` instance. 

I'm sorry the tardiness in the response.
