### ISSUE TITLE
How could I understand the key-value combinations and their meanings in man.simulation_controls?

### ISSUE THREAD

**Issue by maso0310** [daquinterop/Py_DSSATTools#8]
Hello, when I use DSSATTools to simulate rice crop growth, I found that there are many parameters that can be adjusted in man.simulation_controls. However, I am not sure about the meanings of these parameters and the possible values that can be adjusted, as shown in the following items:

```
pars={
    'GENERAL': 'GE',
    'NYERS': 1, 'NREPS': 1, 'START': 'S',
    'SDATE': self.sim_start.strftime('%y%j'), 'RSEED': 2409,
    'SNAME....................': 'DEFAULT', 'SMODEL': 'MZCER',

    'OPTIONS': 'OP',
    'WATER': 'Y', 'NITRO': 'N', 'SYMBI': 'N', 'PHOSP': 'N',
    'POTAS': 'N', 'DISES': 'N', 'CHEM': 'N', 'TILL': 'N',
    'CO2': 'M',

    'METHODS': 'ME',
    'WTHER': 'M', 'INCON': 'M', 'LIGHT': 'E', 'EVAPO': 'R',
    'INFIL': 'S', 'PHOTO': 'C', 'HYDRO': 'R', 'NSWIT': 1,
    'MESOM': 'G', 'MESEV': 'S', 'MESOL': 2, 

    'MANAGEMENT': 'MA',
    'PLANT': 'R', 'IRRIG': self.irrigaton_option,
    'FERTI': self.fertization_option, 'RESID': 'N',
    'HARVS': self.harvest_option,

    'OUTPUTS': 'OU',
    'FNAME': 'N', 'OVVEW': 'Y', 'SUMRY': 'Y', 'FROPT': 1,
    'GROUT': 'Y', 'CAOUT': 'N', 'WAOUT': 'Y', 'NIOUT': 'N',
    'MIOUT': 'N', 'DIOUT': 'N', 'VBOSE': 'Y', 'CHOUT': 'N',
    'OPOUT': 'N', 'FMOPT':'A',
}
```
Could you please tell me where I can find detailed documentation about these parameter settings? Thank you.

**Comment by daquinterop** [comment]
You can use the DSSAT desktop app as guidance. When you're editing an experimental file in the DSSAT, you see that there are different sections in the simulation options. If you go over all the options in the GUI, and the options present in the dict you posted, I'm sure you'll figure out what is the meaning of each key-value component. Overall, for the definitions of all management and simulation options I recommend using the DSSAT GUI as a guidance. 
I post an screenshot of DSSAT as reference. You see how Methods section is defined in the GUI. In that case each key-value pair represents the different options in the GUI and the value selected in the dropdown. 
![image](https://github.com/daquinterop/Py_DSSATTools/assets/40781738/a96a0215-511c-4585-b210-402af081dada)

**Comment by maso0310** [comment]
I understand, thank you very much for your help.
